### PR TITLE
fix: simplify filter query

### LINKED ISSUE #300: Troubleshooting Database Performance
Relevant links
- https://github.com/bula21/mova21-orca/pull/299 - revert from prod

Verify if the database should / can be moved. Make decision and communicate with peers

### PR DESCRIPTION
**Pull request by diegosteiner**
fixes #300

### CODE REVIEW

File: app/controllers/activities_controller.rb [hunk 1]
```diff
@@ -75,13 +75,18 @@ def attach_attachments
...
-                                                                                         languages: [])
-    session[:activity_filter_params] = activity_filter_params if params.key?(:activity_filter)
-    @filter ||= ActivityFilter.new(session[:activity_filter_params] || {})
+    if params.key?(:activity_filter)
+      activity_filter_params = params[:activity_filter].permit(:min_participants_count, :stufe_recommended, :text,
+                                                               :activity_category, :only_booked,
+                                                               tags: [], languages: [])
+      session[:activity_filter_params] = default_filter_params.merge(activity_filter_params)
+    end
+    @filter ||= ActivityFilter.new(session[:activity_filter_params] || default_filter_params)
```
Comment (diegosteiner) [inline app/controllers/activities_controller.rb:96]: Hier sind eigentlich nur die default_filter_params dazugekommen

**Comment by jimmylevell** [comment]
Please verify that only activities with assigned units are displayed publicly

**Review by jimmylevell — APPROVED** [review]
